apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: video-to-audio
spec:
  serviceName: mongo-service
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo:4.0.8
        name: mongo
        volumeMounts:
          - mountPath: "/data/db"
            name: mongo-data
        envFrom:
        - secretRef:
            name: mongo-secret
        ports:
          - containerPort: 27017
        resources: 
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "400Mi"
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: mannual
        resources:
          requests:
            storage: 200Mi