apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: video-to-audio
spec:
  serviceName: mongo-service
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
      containers:
      - image: mongo:4.2
        name: mongo
        volumeMounts:
          - mountPath: "/data/db"
            name: mongo-data
        envFrom:
        - secretRef:
            name: mongo-secret
        ports:
          - containerPort: 27017
        resources: 
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "400Mi"