apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: monitoring
stringData:
  alertmanager.yml: |
      global:
        resolve_timeout: 1m

      route:
        group_by: ['alertname']
        receiver: 'email_notification'

      receivers:
      - name: 'email_notification'
        email_configs:
        - to: 'abhradipserampore@gmail.com'
          from: 'abhradipserampore@gmail.com'
          smarthost: smtp.gmail.com:587
          auth_username: 'abhradipserampore@gmail.com'
          auth_identity: 'abhradipserampore@gmail.com'
          auth_password: 'nwxu zxtw ipio fqwj'
          headers :
            Subject: 'Highly urgent .. .Please look ASAP !! '
          text: '{ { . CommonAnnotations. summary } } '