grafana:
  service:
    type: NodePort
    nodePort: 32000
  adminUser: abhra
  adminPassword: abhradip
  sidecar:
    datasources:
      defaultDatasourceEnabled: true
  additionalDataSources: 
  - name: loki
    type: loki
    url: http://loki-loki-distributed-query-frontend.monitoring:3100

prometheus:
  service:
    type: NodePort
    nodePort: 32001

alertmanager:
  service:
    type: NodePort
    nodePort: 32002
  