grafana:
  service:
    type: NodePort
    nodePort: 32000
  adminUser: abhra
  adminPassword: abhradip

prometheus:
  service:
    type: NodePort
    nodePort: 32001

alertmanager:
  service:
    type: NodePort
    nodePort: 32002
  