apiVersion: v1
kind: Service
metadata:
  labels:
    app: online-shop-green
  name: online-shop-green-svc
  namespace: bluegreen-ns
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: online-shop-green
