apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monitor
  name: monitor-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - image: abhradippaul/nodejs-monitoring
          name: monitor-container
          ports:
            - containerPort: 4000
          resources:
            requests:
              cpu: "10m"
              memory: "20Mi"
            limits:
              cpu: "20m"
              memory: "40Mi"