apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitor
  name: monitor-service
spec:
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
      nodePort: 30004
  selector:
    app: monitor
  type: NodePort