apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-deployment-strategies
  namespace: canary-ns
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: online-shop-svc
                port:
                  number: 3000
