apiVersion: v1
kind: Service
metadata:
  labels:
    app: online-shop
  name: online-shop-svc
  namespace: canary-ns
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: online-shop
