apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: online-shop
    version: v2
  name: online-shop-v2-deploy
  namespace: canary-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: online-shop
      version: v2
  template:
    metadata:
      labels:
        app: online-shop
        version: v2
    spec:
      containers:
        - image: amitabhdevops/online_shop_without_footer
          name: online-shop-container
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 25m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 20Mi
