apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-a-deployment
  name: service-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a-deployment
  template:
    metadata:
      labels:
        app: service-a-deployment
    spec:
      containers:
        - image: abhradippaul/nodejs-tracing:service-a
          name: service-a
          ports:
            - containerPort: 3001
          env:
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: "http://jaeger-collector.traces:14268/api/traces"
            - name: SERVICE_B_URI
              value: "http://b-service"
