apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deployment-strategies
  namespace: recreate-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: online-shop-svc
                port:
                  number: 80
