apiVersion: v1
kind: Service
metadata:
  labels:
    app: recreate
  name: recreate-svc
  namespace: recreate-ns
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: recreate
