replicas: 1
minimumMasterNodes: 1

resources:
  requests:
    cpu: "200m"
    memory: "400Mi"
  limits:
    cpu: "200m"
    memory: "400Mi"

persistence:
  enabled: false

service:
  type: NodePort
  nodePort: 30080