apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend-service
  namespace: voting-app
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend
  type: ClusterIP
