apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: voting-app
  name: backend
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
