apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: cloudacademydevops/frontend:v11
          name: frontend
          ports:
            - containerPort: 8080
          env:
            - name: REACT_APP_APIHOSTPORT
              valueFrom:
                configMapKeyRef:
                  name: frontend-cm
                  key: REACT_APP_APIHOSTPORT
          resources:
            requests:
              cpu: "10m"
              memory: "20Mi"
            limits:
              cpu: "20m"
              memory: "40Mi"
