{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "success slow endpoint",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{path=\"/slow\",status_code=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "slow endpoint request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "irate(http_requests_total{path=\"/slow\", status_code=\"200\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/metrics",
   "type": "stat",
   "description": "Metrics endpoints request count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{path=\"/metrics\",status_code=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed slow endpoint request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{path=\"/slow\",status_code=\"500\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}