grafana:
  service:
    type: NodePort
    nodePort: 32000

prometheus:
  service:
    type: NodePort
    nodePort: 32001

alertmanager:
  service:
    type: NodePort
    nodePort: 32002 
  config:
    global:
      resolve_timeout: 1m

    route:
      group_by: ['alertname']
      receiver: 'email_notification'

    receivers:
      - name: 'email_notification'
        email_configs:
          - to: ''
            from: ''
            smarthost: smtp.gmail.com:587
            auth_username: ''
            auth_identity: ''
            auth_password: ''
            headers :
              Subject: 'Highly urgent .. .Please look ASAP !! '
            text: '{ { . CommonAnnotations. summary } } '