apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: online-shop
  name: online-shop-deploy
  namespace: rollingupdate-ns
spec:
  replicas: 5
  selector:
    matchLabels:
      app: online-shop
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1 #Extra pod
      maxUnavailable: 0 #Unavailable pod
  template:
    metadata:
      labels:
        app: online-shop
    spec:
      containers:
        - image: amitabhdevops/online_shop
          name: online-shop-container
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 25m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 20Mi
