---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-a-deployment
  name: service-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a-deployment
  template:
    metadata:
      labels:
        app: service-a-deployment
    spec:
      containers:
        - image: abhradippaul/nodejs-tracing:service-a
          name: service-a
          ports:
            - containerPort: 3001
          env:
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: "http://jaeger-collector.traces:14268/api/traces"
            - name: SERVICE_B_URI
              value: "http://b-service"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    job: node-api
    app: a-service
  name: a-service
spec:
  ports:
    - name: a-service-port
      port: 80
      protocol: TCP
      targetPort: 3001
      nodePort: 32001
  selector:
    app: service-a-deployment
  type: NodePort

---