---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-b-deployment
  name: service-b-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b-deployment
  template:
    metadata:
      labels:
        app: service-b-deployment
    spec:
      containers:
        - image: abhradippaul/nodejs-tracing:service-b
          name: service-b
          ports:
            - containerPort: 3002
          env:
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: "http://jaeger-collector.traces:14268/api/traces"

            - name: SERVICE_A_URI
              value: "http://a-service"  

---

apiVersion: v1
kind: Service
metadata:
  labels:
    job: node-api
    app: b-service
  name: b-service
spec:
  ports:
    - name: b-service-port
      port: 80
      protocol: TCP
      targetPort: 3001
      nodePort: 32002
  selector:
    app: service-b-deployment
  type: NodePort

---